[pytest]
testpaths = tests
# -q: quiet
# --junitxml: generate junit report for CI/CD tools
# --cov: measure coverage for 'backend' package
# --cov-report term: show coverage in terminal
# --cov-report html: generate html report
addopts = -q --junitxml=artifacts/junit.xml --cov=backend --cov-report=term --cov-report=html:artifacts/coverage_html
python_files = test_*.py
