"""initial_schema

Revision ID: af9cd7d5f46f
Revises: 
Create Date: 2026-02-18 18:58:28.245366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af9cd7d5f46f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('themes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('colors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fonts', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chart_styles', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('preview_image_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_picture_url', sa.String(length=500), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('dashboards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('theme_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_filename', sa.String(length=255), nullable=False),
    sa.Column('dataset_url', sa.String(length=500), nullable=True),
    sa.Column('dataset_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('target_column', sa.String(length=255), nullable=True),
    sa.Column('problem_type', sa.String(length=50), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_count', sa.Integer(), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('layout', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_viewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['theme_id'], ['themes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboards_created_at'), 'dashboards', ['created_at'], unique=False)
    op.create_index(op.f('ix_dashboards_is_public'), 'dashboards', ['is_public'], unique=False)
    op.create_index(op.f('ix_dashboards_user_id'), 'dashboards', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('login_time', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_is_active'), 'sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_sessions_token'), 'sessions', ['token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('default_theme', sa.String(length=50), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_preferences_user_id'), 'user_preferences', ['user_id'], unique=True)
    op.create_table('chart_configurations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('chart_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('x_column', sa.String(length=100), nullable=True),
    sa.Column('y_column', sa.String(length=100), nullable=True),
    sa.Column('color_column', sa.String(length=100), nullable=True),
    sa.Column('aggregation', sa.String(length=50), nullable=True),
    sa.Column('position', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('style', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chart_configurations_dashboard_id'), 'chart_configurations', ['dashboard_id'], unique=False)
    op.create_table('dashboard_shares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('shared_with_user_id', sa.UUID(), nullable=True),
    sa.Column('share_token', sa.String(length=100), nullable=False),
    sa.Column('shared_with_email', sa.String(length=255), nullable=True),
    sa.Column('permission_level', sa.String(length=20), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accessed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_shares_dashboard_id'), 'dashboard_shares', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_dashboard_shares_share_token'), 'dashboard_shares', ['share_token'], unique=True)
    op.create_table('dataset_storage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('column_names', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_storage_dashboard_id'), 'dataset_storage', ['dashboard_id'], unique=True)
    op.create_table('exports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('export_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('download_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exports_dashboard_id'), 'exports', ['dashboard_id'], unique=False)
    op.create_table('insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('insight_type', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insights_dashboard_id'), 'insights', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_insights_priority'), 'insights', ['priority'], unique=False)
    op.create_table('ml_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('test_score', sa.Float(), nullable=False),
    sa.Column('cv_score', sa.Float(), nullable=True),
    sa.Column('training_time', sa.Float(), nullable=True),
    sa.Column('feature_importance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confusion_matrix', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('prediction_samples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hyperparameters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_best_model', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ml_results_dashboard_id'), 'ml_results', ['dashboard_id'], unique=False)
    op.create_index(op.f('ix_ml_results_model_name'), 'ml_results', ['model_name'], unique=False)
    op.create_table('query_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('dashboard_id', sa.UUID(), nullable=True),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('generated_code', sa.Text(), nullable=True),
    sa.Column('generated_pandas_code', sa.Text(), nullable=True),
    sa.Column('result_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('execution_time', sa.Float(), nullable=True),
    sa.Column('was_successful', sa.Boolean(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_query_history_timestamp'), 'query_history', ['timestamp'], unique=False)
    op.create_index(op.f('ix_query_history_user_id'), 'query_history', ['user_id'], unique=False)
    op.create_table('user_activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('dashboard_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('action_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dashboard_id'], ['dashboards.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_activity')
    op.drop_index(op.f('ix_query_history_user_id'), table_name='query_history')
    op.drop_index(op.f('ix_query_history_timestamp'), table_name='query_history')
    op.drop_table('query_history')
    op.drop_index(op.f('ix_ml_results_model_name'), table_name='ml_results')
    op.drop_index(op.f('ix_ml_results_dashboard_id'), table_name='ml_results')
    op.drop_table('ml_results')
    op.drop_index(op.f('ix_insights_priority'), table_name='insights')
    op.drop_index(op.f('ix_insights_dashboard_id'), table_name='insights')
    op.drop_table('insights')
    op.drop_index(op.f('ix_exports_dashboard_id'), table_name='exports')
    op.drop_table('exports')
    op.drop_index(op.f('ix_dataset_storage_dashboard_id'), table_name='dataset_storage')
    op.drop_table('dataset_storage')
    op.drop_index(op.f('ix_dashboard_shares_share_token'), table_name='dashboard_shares')
    op.drop_index(op.f('ix_dashboard_shares_dashboard_id'), table_name='dashboard_shares')
    op.drop_table('dashboard_shares')
    op.drop_index(op.f('ix_chart_configurations_dashboard_id'), table_name='chart_configurations')
    op.drop_table('chart_configurations')
    op.drop_index(op.f('ix_user_preferences_user_id'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_is_active'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_dashboards_user_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_is_public'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_created_at'), table_name='dashboards')
    op.drop_table('dashboards')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('themes')
    # ### end Alembic commands ###
